from fetch_data import fetch_weather_data
from google.cloud import bigquery
from dotenv import load_dotenv
import os
from datetime import datetime, timezone
from google.api_core.exceptions import NotFound

# Load environment variables from .env file
load_dotenv()

# BigQuery Client Initialization
client = bigquery.Client()

# BigQuery Table Setup (Replace with your project, dataset, and table name)
project_id = 'usecase-weather-project'
dataset_id = 'weather_data'
table_id = 'weather_forecast'

def create_table_if_not_exists():
    """Check if the table exists, if not, create it."""
    try:
        # Check if the table exists
        client.get_table(f'{project_id}.{dataset_id}.{table_id}')
        print(f"Table {table_id} already exists.")
    except NotFound:
        # If table doesn't exist, create it
        print(f"Table {table_id} not found. Creating table...")
        
        # Define the schema
        schema = [
            bigquery.SchemaField("city", "STRING"),
            bigquery.SchemaField("temperature", "FLOAT"),
            bigquery.SchemaField("weather", "STRING"),
            bigquery.SchemaField("timestamp", "TIMESTAMP"),
            bigquery.SchemaField("forecast_summary", "STRING"),
        ]
        
        # Define the table
        table_ref = client.dataset(dataset_id).table(table_id)
        
        # Create the table
        table = bigquery.Table(table_ref, schema=schema)
        table = client.create_table(table)
        print(f"Created table {table_id}.")

def insert_weather_data_to_bigquery(weather_data):
    """Insert the weather data into BigQuery."""
    rows_to_insert = []

    for city_data in weather_data:
        summary = city_data.get('weather')[0].get('description', 'No description available')
        forecast_summary = city_data.get('forecast_summary', 'No forecast summary available')


        # Convert timestamp to a string in ISO 8601 format (UTC)
        timestamp = datetime.now(timezone.utc).isoformat()


        rows_to_insert.append({
            'city': city_data['name'],
            'temperature': city_data['main']['temp'],
            'weather': summary,
            'timestamp': timestamp,  # Use the ISO string format
            'forecast_summary': forecast_summary  # The enhanced summary generated by LLM
        })

    # Insert data into BigQuery (Append mode)
    errors = client.insert_rows_json(f'{project_id}.{dataset_id}.{table_id}', rows_to_insert)
    if errors:
        print(f"Error inserting data: {errors}")
    else:
        print("Data inserted successfully into BigQuery.")

def main():
    # Create table if it doesn't exist
    create_table_if_not_exists()

    # Fetch weather data
    weather_data = fetch_weather_data()

    # Print the weather data for verification
    print("Weather Data:", weather_data)

    # Insert the data into BigQuery
    insert_weather_data_to_bigquery(weather_data)

if __name__ == "__main__":
    main()
